### ISSUE TITLE
Official documentation shows no information for algorithms contained in HistogramThresholding.jl

### ISSUE THREAD

**Issue by Ickaser** [zygmuntszpak/ImageBinarization.jl#91]
I was looking for information on the Entropy binarization algorithm, and found the following:

https://zygmuntszpak.github.io/ImageBinarization.jl/stable/reference/

![image](https://user-images.githubusercontent.com/47340776/156649818-97379354-5924-44fd-b368-0f756fd48836.png)

However, that documentation is visible here:

https://juliaimages.org/HistogramThresholding.jl/stable/

**Comment by johnnychen94** [comment]
Thanks for catching this. This might be due to our Documentation CI issue. The latest package version is v0.2.8 while the documentation is still v0.2.3. I'll check it later today.

**Comment by johnnychen94** [comment]
The issue here is that Documenter CI isn't triggered by new tag releases. A github action (TagBot CI) cannot trigger another github action (docs CI) unless ssh key is configured. See also the "TagBot & tagged versions" in https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#GitHub-Actions

For instance, in https://github.com/johnnychen94/JpegTurbo.jl/actions/workflows/docs.yml, there are two docs CI triggered by tags:

<img src="https://user-images.githubusercontent.com/8684355/157164263-5f01e679-db80-4b02-a20f-1b306a6c2e52.png" alt="action" width="1000">

@zygmuntszpak Because TagBot uses [`DOCUMENTER_KEY`](https://github.com/zygmuntszpak/ImageBinarization.jl/blob/3c4ac3a3359ecb94ed0a4a01f4550d2c16718d2a/.github/workflows/TagBot.yml#L15), can you verify that `DOCUMENTER_KEY` secret is correctly configured? If not, you might want to follow https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#travis-ssh

**Comment by johnnychen94** [comment]
closed by 900406f
